---
# Gather stats on installation status
- stat: path=/home/vagrant/app/web/concrete/vendor
  register: composer_libs

# Install composer stuff (concrete/vendor)
- name: Composer dependencies
  composer: command=install working-dir=/home/vagrant/app/web/concrete/
  when: not composer_libs.stat.exists

# Install GruntJS?
- name: Installing GruntJS
  command: npm install -g grunt-cli
  sudo: yes
  args:
    creates: /usr/bin/grunt

# Install NPM modules if build core assets
- name: Install NPM modules for Concrete5 core Build
  command: npm install chdir=/home/vagrant/app/build
  sudo: yes
  args:
    creates: /home/vagrant/app/build/node_modules

# Actually build the assets
- name: Run Concrete5 asset build
  command: grunt release chdir=/home/vagrant/app/build
  sudo: yes
  args:
    creates: /home/vagrant/app/web/concrete/js/app.js

# Copy config files
# @note: trailing slash (config"/") is important in the src so it doesn't copy the whole
# directory, just its contents
- name: Copy application/config/* files
  copy: src=/home/vagrant/app/pagodabox/copies/config/ dest=/home/vagrant/app/web/application/config/

# Copy bootstrap/start.php
- name: Copy application/bootstrap/start.php
  copy: src=/home/vagrant/app/pagodabox/copies/bootstrap/start.php dest=/home/vagrant/app/web/application/bootstrap/start.php

# Run after_exec hook to generate doctrine proxies
- name: Execute after_exec hook (generate doctrine proxies)
  command: php /home/vagrant/app/pagodabox/after_exec.php

# ... And finally, install C5
- name: Install Concrete5 via CLI
  shell: >
    php /home/vagrant/app/pagodabox/install.php \
      --admin-email=change@me.com \
      --admin-password=c5@dmin \
      --db-database={{ shared.dbname }} \
      --db-username={{ shared.dbuser }} \
      --db-password={{ shared.dbpass }} \
      --db-server={{ shared.dbhost }} \
      --core=/home/vagrant/app/web/concrete/ \
      --target=/home/vagrant/app/web/



#- name: Run Concrete5 CLI Installer
#  shell: >
#    php /home/vagrant/app/cli/install-concrete5.php \
#      --admin-email=change@me.com \
#      --admin-password=c5@dmin \
#      --db-database={{ database_name }} \
#      --db-username={{ database_user }} \
#      --db-password={{ database_pass }} \
#      --db-server={{ database_host }} \
#      --core=/home/vagrant/app/web/concrete/ \
#      --target=/home/vagrant/app/web/
