---
- name: Install Apache
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item}}
  notify: restart_apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - ssl

- name: Install self-signed cert for SSL testing
  copy: src=vagrant_apache_ssl.pem dest=/etc/ssl/certs/vagrant_apache_ssl.pem group=root owner=root mode=0644

- name: Purge all existing virtual host configurations
  file: path={{ item }} state=absent
  with_fileglob:
    - /etc/apache2/sites-enabled/*
    - /etc/apache2/sites-available/*

- name: Create virtual host configurations for enabled sites
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item.servername }}.conf
  with_items: virtual_hosts

- name: Create SSL virtual host configurations for enabled sites
  template: src=vhost-ssl.conf.j2 dest=/etc/apache2/sites-available/{{ item.servername }}-ssl.conf
  with_items: virtual_hosts

- name: Enable virtual hosts
  shell: a2ensite {{ item.servername }}.conf
  sudo: yes
  with_items: virtual_hosts
  notify: restart_apache

- name: Enable SSL virtual hosts
  shell: a2ensite {{ item.servername }}-ssl.conf
  sudo: yes
  with_items: virtual_hosts
  notify: restart_apache

- name: Add users to www-data/apache group
  user: name={{ item }} groups=www-data append=yes
  with_items: apache_users