---
php_ppa: ppa:ondrej/php5-5.6

php_packages:
  - php5-cli
  - php5-common
  - php5-dev
  - php-pear
  - php5-mysql
  - php5-readline
  - php5-gd
  - php5-curl

# Extra things to install
php_install_xdebug: false
php_install_phpunit: false
php_install_composer: false
php_install_redis_ext: false

# Just because Redis extension is installed doesn't necessarily
# mean it'll get used for sessions. To configure php.ini to use
# Redis for sessions:
php_sessions_use_redis: false

# Empty list by default, define customizations at the role
# include level (the implementing playbook)
php_ini_settings: []

# Empty by default, but if php_sessions_use_redis == true, this
# will be overridden in the phpredis.yml via an include_vars.
php_ini_session_settings: []

# Actual defaults (always included, but overridable at the
# playbook level w/ php_ini_settings values).
php_ini_defaults:
  - { k: 'short_open_tag', v: 'On' }
