---
- name: Install Apache
  apt: pkg=apache2 state=latest

- name: Install Apache Modules
  apache2_module: state=present name={{ item}}
  notify: restart_apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires

- name: Setup Apache vHost
  template: src=vhost.conf.tpl dest=/etc/apache2/sites-available/000-default.conf
  notify: restart_apache

- name: Add Vagrant user to www-data/apache group
  user: name=vagrant groups=www-data append=yes