---
- name: Update apt
  apt: update_cache=yes

- name: Install system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - curl
    - software-properties-common

- name: Copy locale configuration to /etc/default/locale
  template: src=locale.tpl dest=/etc/default/locale

- name: Configure locale
  shell: locale-gen en_US.UTF-8 && dpkg-reconfigure locales

- name: Configure timezone
  template: src=timezone.tpl dest=/etc/timezone

- name: Configure timezone 2
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes backup=yes