---
- name: Update apt
  apt: update_cache=yes

- name: Install system packages
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - git
    - curl
    - software-properties-common
    - build-essential

- name: Copy locale configuration to /etc/default/locale
  template: src=locale.tpl dest=/etc/default/locale

- name: Configure locale
  shell: locale-gen en_US.UTF-8 && dpkg-reconfigure locales

- name: Configure timezone step 1
  template: src=timezone.tpl dest=/etc/timezone

- name: Configure timezone step 2
  file: src=/usr/share/zoneinfo/{{ system_timezone }} dest=/etc/localtime state=link force=yes backup=yes

# Note: user must already exist in the system!
# http://unix.stackexchange.com/questions/117467/how-to-permanently-set-environmental-variables
- name: Setup environment variables for system users in .profile
  lineinfile: dest=/home/{{ item.user }}/.profile regexp="{{ item.regexp }}" line="{{ item.line }}" state=present insertafter=EOF backup=yes
  with_items: user_env_variables

- name: Setup environment variables for system users in .bashrc
  lineinfile: dest=/home/{{ item.user }}/.bashrc regexp="{{ item.regexp }}" line="{{ item.line }}" state=present insertafter=EOF backup=yes
  with_items: user_env_variables
