---
# https://github.com/bennojoy/mysql/blob/master/tasks/main.yml
- name: Install MySQL
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Ensure MySQL started
  service: name=mysql state=started enabled=true

#- name: Copy .my.cnf file with root credentials
#  template: src=.my.cnf.j2 dest=~/.my.cnf owner=root mode=0600
#  notify: restart_mysql

#- name: Update MySQL root password
#  mysql_user:
#    name: root
#    host: "{{ item }}"
#    password: "root"
#    login_user: root
#    login_password: root
#    check_implicit_admin: yes
#    priv: "*.*:ALL,GRANT"
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost

#- name: Update MySQL root password for all root accounts
#  mysql_user: name=root host={{ item }} password=root
#  with_items:
#    - "{{ ansible_hostname }}"
#    - 127.0.0.1
#    - ::1
#    - localhost
#  when: ansible_hostname != 'localhost'
#
#- name: Update MySQL root password for all root accounts (localhost)
#  mysql_user: name=root host={{ item }} password=root
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - localhost
#  when: ansible_hostname == 'localhost'
#
#
#- name: Update bind address
#  lineinfile: dest=/etc/mysql/my.cnf regexp="{{ item.regexp }}" line="{{ item.line }}"
#  with_items:
#    - { regexp: "bind-address =", line: "bind-address = 0.0.0.0" }
#  notify: restart_mysql
#
#- name: Remove anonymous MySQL users
#  mysql_user: name='' host={{ item }} state=absent
#  with_items:
#    - localhost
#    - "{{ ansible_hostname }}"
#
#- name: Remove test database
#  mysql_db: name=test state=absent
#
#- name: Create database
#  mysql_db: name={{ database_name }} state=present
#
#- name: Create Concrete5 user
#  mysql_user: name={{ database_user }} password={{ database_pass }}
#    priv="*.*:ALL" state=present host="%"






#- name: Update MySQL root password
#  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ database_pass }} login_user=root login_password={{ database_pass }} priv=*.*:ALL,GRANT
#  with_items:
#    - 127.0.0.1
#    - ::1
#    - localhost

#- name: Setup remote root access
#  mysql_user: name=root password={{ database_pass }} priv=*.*:ALL,GRANT state=present login_user={{ database_user }} login_password={{ database_pass }}

#- name: Install MySQL Timezone Tables
#  shell: mysql_tzinfo_to_sql 2>/dev/null /usr/share/zoneinfo | mysql -u root --password=root mysql 2>/dev/null