---
- name: Check nodejs is installed
  shell: $SHELL -lc "which nodejs"
  sudo: true
  register: nodejs_installed
  ignore_errors: yes

- name: Register NodeJS PPA
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -
  when:
    - nodejs_installed.rc == 1

- name: Install NodeJS and NPM
  apt: pkg=nodejs state=installed update_cache=yes
  when:
    - nodejs_installed.rc == 1