---
- hosts: all
  sudo: yes

  vars:
    # App Related
    httpd_doc_root: "/home/vagrant/app/web"
    database_name: concrete5_site
    database_host: "127.0.0.1"
    database_user: concrete5
    database_pass: concrete5

    # System Related
    timezone: UTC
    php_ppa: php5
    php_packages: ["php5-cli","php-pear","php5-mysql","php5-readline","php5-gd","php5-curl","php5-xdebug"]

    # GeerlingGuy MySQL role
#    mysql_root_password: root
#    mysql_databases:
#      - name: concrete5_site
#        encoding: utf8
#        collation: utf8_general_ci
#    mysql_users:
#      - name: concrete5
#        host: "%"
#        password: concrete5
#        priv: "*.*:ALL"

  roles:
    - init
    - apache
    - php
    - mysql
    - ruby
    - nodejs
#    - concrete5
#    - geerlingguy/mysql

 #
 # Good references
 # https://github.com/M4nu/ansible/blob/master/nodejs/main.yml
 #