---
- hosts: all
  sudo: yes

  vars:
    # Edit these if need be
    shared:
      dbhost: "127.0.0.1"
      dbuser: concrete5
      dbpass: concrete5
      dbname: dev_site

  roles:
    - system

    - role: apache
      apache_users:
        - vagrant
      virtual_hosts:
        - servername: "vagrant" # or "domain.com"
          serveralias: "*"
          docroot: "/home/vagrant/app/web"
          env_vars:
            - { name: "DATABASE1_HOST", value: "{{ shared.dbhost }}" }
            - { name: "DATABASE1_USER", value: "{{ shared.dbuser }}" }
            - { name: "DATABASE1_PASS", value: "{{ shared.dbpass }}" }
            - { name: "DATABASE1_NAME", value: "{{ shared.dbname }}" }

    - role: geerlingguy.mysql
      mysql_root_password: root
      mysql_databases:
        - name: "{{ shared.dbname }}"
          encoding: utf8
          collation: utf8_general_ci
      mysql_users:
        - { name: "{{ shared.dbuser }}", host: "%", password: "{{ shared.dbpass }}", priv: "{{ shared.dbname }}.*:ALL" }

    - redis

    - php

    - nodejs

    - role: rbenv
      rbenv_user: vagrant

    - role: concrete5
      run_composer: true
      build_core_assets: true
      apply_patches: true