---
- hosts: all
  sudo: yes

  vars:
    # Edit these if need be
    shared:
      dbhost: "127.0.0.1"
      dbuser: concrete5
      dbpass: concrete5
      dbname: dev_site

  roles:
    - role: system
      user_env_variables:
        - { user: vagrant, regexp: "export DATABASE1_HOST=", line: "export DATABASE1_HOST={{ shared.dbhost }}" }
        - { user: vagrant, regexp: "export DATABASE1_USER=", line: "export DATABASE1_USER={{ shared.dbuser }}" }
        - { user: vagrant, regexp: "export DATABASE1_PASS=", line: "export DATABASE1_PASS={{ shared.dbpass }}" }
        - { user: vagrant, regexp: "export DATABASE1_NAME=", line: "export DATABASE1_NAME={{ shared.dbname }}" }

    - role: apache
      apache_users:
        - vagrant
      virtual_hosts:
        - servername: "vagrant" # or "domain.com"
          serveralias: "*"
          docroot: "/home/vagrant/app/web"
          env_vars:
            - { name: "DATABASE1_HOST", value: "{{ shared.dbhost }}" }
            - { name: "DATABASE1_USER", value: "{{ shared.dbuser }}" }
            - { name: "DATABASE1_PASS", value: "{{ shared.dbpass }}" }
            - { name: "DATABASE1_NAME", value: "{{ shared.dbname }}" }
          php_env_vars:
            - { name: "upload_max_filesize", value: "8M" }
            - { name: "post_max_size", value: "8M" }
            - { name: "max_input_time", value: "300" }
            - { name: "max_execution_time", value: "300" }

    - role: geerlingguy.mysql
      mysql_root_password: root
      mysql_databases:
        - name: "{{ shared.dbname }}"
          encoding: utf8
          collation: utf8_general_ci
      mysql_users:
        - { name: "{{ shared.dbuser }}", host: "%", password: "{{ shared.dbpass }}", priv: "{{ shared.dbname }}.*:ALL" }

    - redis

    - php

    - role: nodejs
      npm_global_packages:
        - gulp
        - bower
      npm_package_json:
        install: true
        path: "/home/vagrant/app"

    - role: rbenv
      rbenv_user: vagrant
      rbenv_default_gems:
        - bundler
        - compass

    - role: concrete5
      run_composer: true
      build_core_assets: true
      apply_patches: true

  # Random stuff after main dependencies are provisioned
  tasks:
    - name: Install MySQL timezone tables
      shell: mysql_tzinfo_to_sql 2>/dev/null /usr/share/zoneinfo | mysql -u root --password=root mysql 2>/dev/null