---
- name: Add PHP5 PPA repository
  apt_repository: repo="{{ php_ppa }}" state=present update_cache=yes

- name: Install PHP5 core
  apt: pkg=php5 state=present

- name: Install PHP5
  apt: pkg=php5-common state=present

- name: Install PHP5-cli
  apt: pkg=php5-cli state=present

- name: Install PHP packages
  apt: pkg="{{ item }}" state=present
  with_items: "{{php_packages}}"

- include: xdebug.yml
  when: php_install_xdebug == true

- include: composer.yml
  when: php_install_composer == true

- include: phpunit.yml
  when: php_install_phpunit == true

# note: we can build the extension, but Redis is still expected to be available!
- include: phpredis.yml
  when: php_install_redis_ext == true

- name: Copy php.ini for HTTPD
  copy: src=php.ini-httpd dest=/etc/php5/apache2/php.ini

- name: Copy php.ini for CLI
  copy: src=php.ini-cli dest=/etc/php5/cli/php.ini

- name: Customize php.ini for HTTPD
  lineinfile: dest=/etc/php5/apache2/php.ini regexp='{{ item.k }} =' line='{{ item.k }} = {{ item.v }}'
  with_items: "{{ (php_ini_defaults + php_ini_session_settings) + php_ini_settings }}"

- name: Customize php.ini for CLI
  lineinfile: dest=/etc/php5/cli/php.ini regexp='{{ item.k }} =' line='{{ item.k }} = {{ item.v }}'
  with_items: "{{ (php_ini_defaults + php_ini_session_settings) + php_ini_settings }}"
