---
- name: Add PHP5 PPA repository
  apt_repository: repo={{ php_ppa }} state=present update_cache=yes

- name: Install PHP5
  apt: pkg=php5 state=present

- name: Install PHP5-cli
  apt: pkg=php5-cli state=present

- name: Install PHP packages
  apt: pkg={{ item }} state=present
  with_items: php_packages

- include: xdebug.yml
  when: install_xdebug == true

- include: composer.yml
  when: install_composer == true

- include: phpunit.yml
  when: install_phpunit == true

# note: we can build the extension, but Redis is still expected to be available!
- include: phpredis.yml
  when: install_phpredis == true

# php.ini settings for Apache
- name: php.ini configs - HTTPD
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="{{ item.key }} =" line="{{ item.key }} = {{ item.val }}" backup=yes
  with_items: "{{ phpINI_httpd_defaults + phpINI_httpd_settings }}"

# php.ini settings for CLI
- name: php.ini configs - CLI
  lineinfile: dest=/etc/php5/cli/php.ini regexp="{{ item.key }} =" line="{{ item.key }} = {{ item.val }}" backup=yes
  with_items: "{{ phpINI_cli_defaults + phpINI_cli_settings }}"