---
- name: Checkout phpredis build directory
  git:
    repo: https://github.com/phpredis/phpredis.git
    dest: /usr/local/src/phpredis
    version: 2.2.7
    update: no

- name: Build phpredis extension
  shell: cd /usr/local/src/phpredis && phpize && ./configure && make && make install
  sudo: yes
  args:
    chdir: /usr/local/src/phpredis
    creates: /usr/local/src/phpredis/build
  register: phpredis_result

- name: Add phpredis.ini
  template: src=redis.ini.j2 dest=/etc/php5/mods-available/redis.ini owner=root group=root mode=0644

- name: Enable phpredis module with php5enmod
  shell: php5enmod redis
  sudo: yes
  when: phpredis_result|changed

# If php_sessions_redis == true, we OVERWRITE the php_ini_session_settings
- name: Override php_ini_session_settings with Redis definitions
  include_vars: php_ini_session_redis.yml
  when: php_sessions_use_redis == true
