---
- name: Install Ruby-dev for dependencies to build
  apt: pkg=ruby-dev state=present

- name: Install RubyGems
  gem: name={{ item }} state=present user_install=yes include_dependencies=yes
  become: yes
  become_user: vagrant
  with_items: ruby_default_gems
