---
- name: Install Ruby-dev for dependencies to build
  apt: pkg=ruby-dev state=present

- name: Install RubyGems
  gem: name={{ item }} state=present user_install=yes include_dependencies=yes
  become: yes
  become_user: "{{ ruby_user }}"
  with_items: ruby_default_gems

# http://guides.rubygems.org/faqs/#user-install
- name: Setup Ruby Gems in Path Variable
  lineinfile: dest=/home/{{ ruby_user }}/.bashrc regexp="(ruby -rubygems -e 'puts Gem.user_dir')" line="PATH=\"$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH\"" state=present insertafter=EOF